---
name: cli-package

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to run this workflow in
        type: environment
        default: Prod
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    # environment is used to access the secrets for Azure credentials
    # to sign in to a container registry to re-use a dev container image as a build cache
    environment: ${{ inputs.environment || 'Prod'}}
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Build and run dev container task
        uses: ./.github/actions/devcontainer_run_command
        with:
          COMMAND: |
            # Validate installation and showing help output
            cd cli
            make pip-install install-cli
            source <(_TRE_COMPLETE=bash_source tre)
            tre --help
          DEVCONTAINER_TAG: latest
          CI_CACHE_ACR_NAME: ${{ secrets.ACR_NAME}}
          AZURE_CLIENT_ID: ${{ secrets. AZURE_CLIENT_ID }}
          AZURE_TENANT_ID:  ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_ENVIRONMENT: ${{ vars.AZURE_ENVIRONMENT }}

      - name: Create the CLI package
        uses: ./.github/actions/devcontainer_run_command
        with:
          COMMAND: |
            # Create the python wheel
            cd cli
            sudo make build-package
          DEVCONTAINER_TAG: latest
          CI_CACHE_ACR_NAME: ${{ secrets.ACR_NAME}}
          AZURE_CLIENT_ID:  ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets. AZURE_SUBSCRIPTION_ID }}
          AZURE_ENVIRONMENT: ${{ vars.AZURE_ENVIRONMENT }}

      - name: Upload Wheel as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tre-cli
          path: dist/tre-*.whl
